In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
from stretch_mujoco import StretchMujocoSimulator
from stretch_mujoco.robocasa_gen import model_generation_wizard
model, xml = model_generation_wizard(
    task=task_name,
    layout=layout_id,
    style=style_id,
    wrtie_to_file=filename,
)
robot_sim = StretchMujocoSimulator(model=model)
robot_sim.start()

ModuleNotFoundError: No module named 'robosuite'

In [1]:
from stretch_mujoco_wrapper import StretchMujocoSimulator

In [4]:
!ls

__init__.py  rwlock.py			stretch_sim_driver.py  utils.py
__pycache__  stretch_mujoco_wrapper.py	template.ipynb


In [2]:
robot_sim = StretchMujocoSimulator('../scene/scene.xml')
robot_sim.get_actuator_names()

['left_wheel_vel',
 'right_wheel_vel',
 'lift',
 'arm',
 'wrist_yaw',
 'wrist_pitch',
 'wrist_roll',
 'gripper',
 'head_pan',
 'head_tilt']

In [3]:
robot_sim.start() # This will start the simulation and open Mujoco-Viewer window

Starting Stretch Mujoco Simulator...


In [58]:
actuator_name = 'head_pan'
actuator = robot_sim.mjdata.actuator(actuator_name)

In [59]:

f1 = actuator.force[0]
f2 = actuator.velocity[0]
print(f1)
print(f2)
# robot_sim.mjdata.actuator('lift').force

4.90996409691846e-05
-1.4468501689936314e-14


In [ ]:
dir(robot_sim.mjdata.sensordata)
print(robot_sim.mjdata.sensordata)
print(robot_sim.mjdata.actuator_force)
dir(robot_sim.mjdata.sensor)

[-2.58141690e-11 -3.11922542e-09  9.20961401e-07  1.85019300e-04
  3.32189756e-02 -9.80994375e+00]
[-7.21372066e-04 -4.18774860e-04  2.91203582e+00  1.04787291e-02
  4.62188432e-03  2.66309625e-01  1.46623047e-03  4.80404696e-02
  4.90995064e-05  4.52001030e-02]


AttributeError: 'builtin_function_or_method' object has no attribute 'data'

In [ ]:
# force
id = actuator.id
f1 = actuator.force
f2 = robot_sim.mjdata.actuator_force[id]
print(f1.item())
print(f2)
# robot_sim.mjdata.actuator('lift').force

0.07613136728805969
0.07613136728805969


In [32]:
dir(robot_sim.mjdata.actuator('lift'))
robot_sim.mjdata.actuator('lift').__class__


mujoco._structs._MjDataActuatorViews

In [20]:
force_applied = robot_sim.mjdata.actuator_force
force_applied

array([-4.98027815e-05, -1.63300045e-04,  2.91203461e+00,  5.70328001e-04,
       -8.98560025e-04,  2.66227496e-01,  1.89734023e-03, -6.40745801e-04,
        4.84055080e-05,  4.52009629e-02])

In [17]:
robot_sim.home()

In [6]:
robot_sim.stow()

In [ ]:
robot_sim.move_to('lift',0.6)

In [ ]:
robot_sim.move_by('head_pan',0.1)

In [ ]:
robot_sim.move_to('head_pan',1)

In [ ]:
robot_sim.set_base_velocity(0.3,-0.1)
print(robot_sim.status)
print(robot_sim.status['base']['x_vel'])
print(robot_sim.status['base']['y_vel'])

In [ ]:
for key, value in robot_sim.status.items():
    print(key, value)

In [ ]:
robot_sim.set_base_velocity(0.3,-0.5)
print(robot_sim.status)

In [ ]:
robot_sim.set_base_velocity(0.0,0.0)
print(robot_sim.status)

In [ ]:
camera_data = robot_sim.pull_camera_data()
print(camera_data)

In [ ]:
robot_sim.stop()

In [ ]:
from stretch_mujoco import StretchMujocoSimulator
from stretch_mujoco.robocasa_gen import model_generation_wizard
model, xml = model_generation_wizard(
    task=task_name,
    layout=layout_id,
    style=style_id,
    wrtie_to_file=filename,
)
robot_sim = StretchMujocoSimulator(model=model)
robot_sim.start()

In [ ]:
import importlib.resources as importlib_resources
import pkg_resources
import urchin as urdf_loader
models_path = pkg_resources.resource_filename("stretch_mujoco", "models")
default_scene_xml_path = models_path + "/scene.xml"
default_robot_xml_path = models_path + "/stretch.xml"

pkg_path = str(importlib_resources.files("stretch_urdf"))
model_name = "SE3"  # RE1V0, RE2V0, SE3
tool_name = "eoa_wrist_dw3_tool_sg3"  # eoa_wrist_dw3_tool_sg3, tool_stretch_gripper, etc
urdf_file_path = pkg_path + f"/{model_name}/stretch_description_{model_name}_{tool_name}.urdf"
mesh_files_directory_path = pkg_path + f"/{model_name}/meshes"

urdf = urdf_loader.URDF.load(urdf_file_path, lazy_load_meshes=True)
robot = urdf.copy()
# for iter in robot.actuated_joints:
#     print(iter.name)
# print(len(robot.links))
# lk_cfg = {
#     "joint_wrist_yaw": cfg["wrist_yaw"],
#     "joint_wrist_pitch": cfg["wrist_pitch"],
#     "joint_wrist_roll": cfg["wrist_roll"],
#     "joint_lift": cfg["lift"],
#     "joint_arm_l0": cfg["arm"] / 4,
#     "joint_arm_l1": cfg["arm"] / 4,
#     "joint_arm_l2": cfg["arm"] / 4,
#     "joint_arm_l3": cfg["arm"] / 4,
#     "joint_head_pan": cfg["head_pan"],
#     "joint_head_tilt": cfg["head_tilt"],
# }
# if "gripper" in cfg.keys():
#     lk_cfg["joint_gripper_finger_left"] = cfg["gripper"]
#     lk_cfg["joint_gripper_finger_right"] = cfg["gripper"]
# robot.link_fk(lk_cfg, link=link_name)
fk = robot.link_fk()
n = 1
print(robot.links[n].name)
print(fk[robot.links[n]])
# print(fk())


joint_right_wheel
joint_left_wheel
joint_lift
joint_head_pan
joint_arm_l3
joint_head_tilt
joint_arm_l2
joint_arm_l1
joint_arm_l0
joint_wrist_yaw
joint_wrist_pitch
joint_wrist_roll
joint_gripper_finger_right
joint_gripper_finger_left
base_link
[[ 1.00000000e+00 -1.27169824e-16 -4.80064671e-17  0.00000000e+00]
 [ 4.80060000e-17 -3.67320510e-06  1.00000000e+00 -1.70350000e-01]
 [-1.27170000e-16 -1.00000000e+00 -3.67320510e-06  5.08000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [2]:
cc = dict(
    wrist_pitch = 1,
)
if 'wrist_pitch' in cc:
    print('true')

true


In [1]:
from ament_index_python.packages import get_package_share_path

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import Command, LaunchConfiguration
import launch_ros.descriptions
from launch_ros.actions import Node
import launch_ros

In [2]:
package_share_path = get_package_share_path('stretch_mujoco_ros2')
package_share_path

PackageNotFoundError: "package 'stretch_mujoco_ros2' not found, searching: ['/opt/ros/humble']"

In [14]:
dd = {
    1:1,
    'b':2,
    'c':3
}

'b' in dd.keys()

'depth' in "cam_depth"

True

In [ ]:
# !pip install mujoco
# !pip install mujoco_mjx
# !pip install brax


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 12.5 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.1/105.1 MB 11.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 13.3 MB/s eta 0:00:00a 0:00:01
  Using cached mujoco-3.2.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 13.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.9/71.9 KB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.6/37.6 MB 13.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 13.6 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.3
    Uninstalling numpy-1.23.3:
      Successfully uninstalled numpy-1.23.3
  Attempting uninstall: scipy
    Found existing installation: scipy 1.8.0
    Not uninstalling scipy at /usr/lib/python3/dist-package