In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
from stretch_mujoco import StretchMujocoSimulator
from stretch_mujoco.robocasa_gen import model_generation_wizard
model, xml = model_generation_wizard(
    task=task_name,
    layout=layout_id,
    style=style_id,
    wrtie_to_file=filename,
)
robot_sim = StretchMujocoSimulator(model=model)
robot_sim.start()

ModuleNotFoundError: No module named 'robosuite'

In [2]:
from stretch_mujoco_wrapper import StretchMujocoSimulator
import threading

In [2]:
!ls

__init__.py  interaction_node.ipynb  stretch_mujoco_wrapper.py	template.ipynb
__pycache__  rwlock.py		     stretch_sim_driver.py	utils.py


In [3]:
robot_sim = StretchMujocoSimulator('../scene/scene.xml')
# robot_sim.get_actuator_names()

In [4]:
robot_sim.start() # This will start the simulation and open Mujoco-Viewer window

Starting Stretch Mujoco Simulator...


In [5]:
robot_sim.mjdata.qpos[:] 

array([ 5.09781213e+00, -9.46799043e-01, -8.23295567e-04,  9.99997738e-01,
       -6.79523407e-07,  1.69241820e-03, -1.28836794e-03,  3.76355084e-03,
       -1.03215127e-04,  5.92624564e-01,  2.49991296e-02,  2.49991282e-02,
        2.49991292e-02,  2.49991317e-02,  4.50578519e-05, -5.32458592e-03,
       -9.49574586e-05,  1.60867462e-07,  1.61373619e-06, -5.08532720e-04,
       -8.84376073e-06,  1.60428158e-06,  4.08065719e-08, -8.89483100e-10,
       -4.99014698e-06, -4.52002169e-03,  9.78279199e-05,  9.90520564e-04,
        1.71939312e-03, -1.82284866e-04, -1.07465497e-03, -9.14823169e-04,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -2.49480833e-16, -2.49480833e-16,
        0.00000000e+00,  0.00000000e+00, -2.49480833e-16, -2.49480833e-16,
        0.00000000e+00,  0.00000000e+00, -2.49480833e-16, -2.49480833e-16,
       -2.53307555e-16, -2.53307555e-16, -2.53307555e-16, -2.53307555e-16,
        0.00000000e+00,  

In [7]:
print(type(robot_sim.mjmodel.keyframe("home").ctrl))

<class 'numpy.ndarray'>


In [6]:
actuator_name = 'head_pan'
actuator = robot_sim.mjdata.actuator(actuator_name)

In [7]:

f1 = actuator.force[0]
f2 = actuator.velocity[0]
print(f1)
print(f2)
# robot_sim.mjdata.actuator('lift').force

4.9256617645225144e-05
-6.744928051878829e-05


In [ ]:
dir(robot_sim.mjdata.sensordata)
print(robot_sim.mjdata.sensordata)
print(robot_sim.mjdata.actuator_force)
dir(robot_sim.mjdata.sensor)

[-2.58141690e-11 -3.11922542e-09  9.20961401e-07  1.85019300e-04
  3.32189756e-02 -9.80994375e+00]
[-7.21372066e-04 -4.18774860e-04  2.91203582e+00  1.04787291e-02
  4.62188432e-03  2.66309625e-01  1.46623047e-03  4.80404696e-02
  4.90995064e-05  4.52001030e-02]


AttributeError: 'builtin_function_or_method' object has no attribute 'data'

In [ ]:
# force
id = actuator.id
f1 = actuator.force
f2 = robot_sim.mjdata.actuator_force[id]
print(f1.item())
print(f2)
# robot_sim.mjdata.actuator('lift').force

0.07613136728805969
0.07613136728805969


In [32]:
dir(robot_sim.mjdata.actuator('lift'))
robot_sim.mjdata.actuator('lift').__class__


mujoco._structs._MjDataActuatorViews

In [20]:
force_applied = robot_sim.mjdata.actuator_force
force_applied

array([-4.98027815e-05, -1.63300045e-04,  2.91203461e+00,  5.70328001e-04,
       -8.98560025e-04,  2.66227496e-01,  1.89734023e-03, -6.40745801e-04,
        4.84055080e-05,  4.52009629e-02])

In [21]:
robot_sim.home()

In [22]:
robot_sim.stow()

In [10]:
robot_sim.move_to('lift',0.6)

In [ ]:
robot_sim.move_by('head_pan',0.1)

In [26]:
robot_sim.move_by('base_rotate',0.2)

In [25]:
robot_sim.move_by('base_translate',-1)

In [27]:
import threading
def mbr():
    robot_sim.move_by('base_rotate',-1)
def mbt():
    robot_sim.move_by('base_translate',2)

threading.Thread(target=mbr, ).start()
import time
time.sleep(0.4)
threading.Thread(target=mbt, ).start()

In [ ]:
robot_sim.move_to('head_pan',1)

In [ ]:
robot_sim.set_base_velocity(0.3,-0.1)
print(robot_sim.status)
print(robot_sim.status['base']['x_vel'])
print(robot_sim.status['base']['y_vel'])

In [ ]:
for key, value in robot_sim.status.items():
    print(key, value)

In [ ]:
robot_sim.set_base_velocity(0.3,-0.5)
print(robot_sim.status)

In [ ]:
robot_sim.set_base_velocity(0.0,0.0)
print(robot_sim.status)

In [ ]:
camera_data = robot_sim.pull_camera_data()
print(camera_data)

In [27]:
robot_sim.stop()

: 

In [ ]:
from stretch_mujoco import StretchMujocoSimulator
from stretch_mujoco.robocasa_gen import model_generation_wizard
model, xml = model_generation_wizard(
    task=task_name,
    layout=layout_id,
    style=style_id,
    wrtie_to_file=filename,
)
robot_sim = StretchMujocoSimulator(model=model)
robot_sim.start()

In [ ]:
import importlib.resources as importlib_resources
import pkg_resources
import urchin as urdf_loader
models_path = pkg_resources.resource_filename("stretch_mujoco", "models")
default_scene_xml_path = models_path + "/scene.xml"
default_robot_xml_path = models_path + "/stretch.xml"

pkg_path = str(importlib_resources.files("stretch_urdf"))
model_name = "SE3"  # RE1V0, RE2V0, SE3
tool_name = "eoa_wrist_dw3_tool_sg3"  # eoa_wrist_dw3_tool_sg3, tool_stretch_gripper, etc
urdf_file_path = pkg_path + f"/{model_name}/stretch_description_{model_name}_{tool_name}.urdf"
mesh_files_directory_path = pkg_path + f"/{model_name}/meshes"

urdf = urdf_loader.URDF.load(urdf_file_path, lazy_load_meshes=True)
robot = urdf.copy()
# for iter in robot.actuated_joints:
#     print(iter.name)
# print(len(robot.links))
# lk_cfg = {
#     "joint_wrist_yaw": cfg["wrist_yaw"],
#     "joint_wrist_pitch": cfg["wrist_pitch"],
#     "joint_wrist_roll": cfg["wrist_roll"],
#     "joint_lift": cfg["lift"],
#     "joint_arm_l0": cfg["arm"] / 4,
#     "joint_arm_l1": cfg["arm"] / 4,
#     "joint_arm_l2": cfg["arm"] / 4,
#     "joint_arm_l3": cfg["arm"] / 4,
#     "joint_head_pan": cfg["head_pan"],
#     "joint_head_tilt": cfg["head_tilt"],
# }
# if "gripper" in cfg.keys():
#     lk_cfg["joint_gripper_finger_left"] = cfg["gripper"]
#     lk_cfg["joint_gripper_finger_right"] = cfg["gripper"]
# robot.link_fk(lk_cfg, link=link_name)
fk = robot.link_fk()
n = 1
print(robot.links[n].name)
print(fk[robot.links[n]])
# print(fk())


joint_right_wheel
joint_left_wheel
joint_lift
joint_head_pan
joint_arm_l3
joint_head_tilt
joint_arm_l2
joint_arm_l1
joint_arm_l0
joint_wrist_yaw
joint_wrist_pitch
joint_wrist_roll
joint_gripper_finger_right
joint_gripper_finger_left
base_link
[[ 1.00000000e+00 -1.27169824e-16 -4.80064671e-17  0.00000000e+00]
 [ 4.80060000e-17 -3.67320510e-06  1.00000000e+00 -1.70350000e-01]
 [-1.27170000e-16 -1.00000000e+00 -3.67320510e-06  5.08000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
